language: objective-c
osx_image: xcode8.2

cache:
    timeout: 300
    bundler: true
    cocoapods: true
    directories:
        - vendor/bundle

podfile: Podfile

before_install:
    - export LANG=en_US.UTF-8
    # pre-starting the simulator
    - xcrun instruments -w "iPhone 7 (10.2) [" || true

install:
    - bundle install --path vendor/bundle # to cache vendor/bundle
    - bundle exec pod repo update

before_script:
    - "$APP_NAME/Scripts/add-key.sh"

script:
    - travis_wait 30 $APP_NAME/Scripts/test.sh

#before_cache:
    #- somescript.sh

#after_success:
    #- somescript.sh

#after_failure:
    #- somescript.sh

#before_deploy:
    #- somescript.sh

deploy:
    provider: script
    script: travis_wait 30 $APP_NAME/Scripts/sign-and-upload.sh $DEVELOP_BRANCH $DEVELOP_LANE
    on:
        branch: $DEVELOP_BRANCH

deploy:
    provider: script
    script: travis_wait 30 $APP_NAME/Scripts/sign-and-upload.sh $RELEASE_BRANCH $RELEASE_LANE
    on:
        branch: $RELEASE_BRANCH

#after_deploy:
    #- somescript.sh

after_script:
    - "$APP_NAME/Scripts/remove-key.sh"

notifications:
    #hipchat:
        #rooms: XXX
        #template:
            #- '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
            #(<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
            #format: html
    email:
        recipients:
            - vladimir.goncharov@flatstack.com
        on_success: always
        on_failure: always
